[Jobs] Fix edge case where entrypoint finishes before `getpid` call (#30066)
When running a load test for Jobs, we use the minimal entrypoint script echo hello. This occasionally (happened after ~1000 jobs) triggers a race condition where the process exits before we get its pgid internally, causing the following error buried in the worker logs:

2022-11-07 12:31:10,305	ERROR job_manager.py:405 -- Got unexpected exception while trying to execute driver command. Traceback (most recent call last):
  File "/Users/archit/ray/python/ray/dashboard/modules/job/job_manager.py", line 366, in run
    child_process = self._exec_entrypoint(log_path)
  File "/Users/archit/ray/python/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/Users/archit/ray/python/ray/dashboard/modules/job/job_manager.py", line 231, in _exec_entrypoint
    child_pgid = os.getpgid(child_pid)
ProcessLookupError: [Errno 3] No such process
This PR
- Propagates the error correctly to the JobStatus, which would have sped up debugging.
- Catches the exception to fix the error. We only get the pgid to start a new process that kills the process group, so if the child process is already dead we don't need to start the new process.

Signed-off-by: Weichen Xu <weichen.xu@databricks.com>