[Error message] print a better message when allow_multiple is given for non-client mode. (#29843)
Signed-off-by: SangBin Cho <rkooo567@gmail.com>

Instead of

```
RuntimeError: Unknown keyword argument(s): allow_multiple
```

It prints
```
RuntimeError: `allow_multiple` argument is passed to `ray.init` when the ray client is not used (https://docs.ray.io/en/master/cluster/running-applications/job-submission/ray-client.html#connect-to-multiple-ray-clusters-experimental). Do not pass the `allow_multiple` to `ray.init` to fix the issue.
```

Signed-off-by: Weichen Xu <weichen.xu@databricks.com>